### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by benjimeltzer** [parautenbach/Home-Automation#1]
Hi Pieter!

I've been trying to find your contact details all over the internet (the closest I got was through your website :():

<img width="1282" alt="Screenshot 2020-12-23 at 15 35 14" src="https://user-images.githubusercontent.com/11029893/103000893-98da6e80-4534-11eb-9aab-d5cab9de1056.png">

For lack of a better option, reaching out here. Would love to connect if/when you're available. Happy to reach out through website!

**Comment by parautenbach** [comment]
I've retracted my original message since I missed this was logged as an issue. :-)

I hope you've seen it and captured my email address. Otherwise, my contact form on www.whatsthatlight.com is working again so you can safely exchange details via that channel.
